affinity: {}
deployment:
  replicas: 1
image:
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: funkypenguin/cardano-node-docker
  tag: latest
livenessProbe:
  enabled: true
  failureThreshold: 6
  initialDelaySeconds: 120
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
nodeSelector: {}
podAnnotations: {}
readinessProbe:
  enabled: true
  failureThreshold: 6
  initialDelaySeconds: 30
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 3
resources:
  requests:
    cpu: 10m
    memory: 32Mi
securityContext:
  enabled: true
  fsGroup: 65534
  fsUser: 65534
  runAsUser: 65534
  runAsGroup: 65534


producer:
  replicas: 1
  persistence:
    size: 10Gi
    accessModes:
      - ReadWriteOnce
  resources:
    requests:
      cpu: 0.1
      memory: 2Gi
  service:
    annotations: {}
    externalTrafficPolicy: Cluster
    extraPorts: []
    loadBalancerIP: null
    nodePorts:
      http: ""
    port: 3000
    type: ClusterIP
    
relay:
  replicas: 2
  persistence:
    size: 10Gi
    accessModes:
      - ReadWriteOnce
  resources:
    requests:
      cpu: 0.1
      memory: 2Gi
  service:
    annotations: {}
    externalTrafficPolicy: Cluster
    extraPorts: []
    loadBalancerIP: null
    nodePorts:
      http: ""
    port: 3000
    type: LoadBalancer # Note that's only the relayservice which gets publically exposed
    loadBalancerIP: '159.89.222.0' # You may only be able to identify this _after_ deploying it
              
monitoring:
  pod:
    scrape: false
pod:
  bpnode:
    securityContext: {}
  relaynode:
    securityContext: {}