---
# Source: ada-stake-pool/templates/configmap.yaml
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  labels:
    app: RELEASE-NAME-ada-stake-pool
    chart: "ada-stake-pool-0.0.1-pre1"
    heritage: "Helm"
    release: "RELEASE-NAME"
  name: RELEASE-NAME-ada-stake-pool
data:
  # example.property.1: hello
  # example.property.file: |-
  #   property.1=value-1
  #   property.2=value-2
