---
# Source: ada-stake-pool/templates/pvc-bpnode.yaml
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: RELEASE-NAME-ada-stake-pool-bpnode
  annotations:
    volume.alpha.kubernetes.io/storage-class: "generic"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "50Gi"
