---
# Source: ada-stake-pool/templates/service-account.yaml
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "__SERVICE_ACCOUNT_NAME__"
  namespace: "default"
  labels:
    app: RELEASE-NAME-ada-stake-pool
    chart: "ada-stake-pool-0.0.1-pre1"
    heritage: "Helm"
    release: "RELEASE-NAME"
