---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: producer
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: {{ template "ada-stake-pool.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
