---
apiVersion: "v1"
kind: "Secret"
metadata:
  labels:
    app: {{ template "ada-stake-pool.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "ada-stake-pool.fullname" . }}
data:
#  An example of creating a secret based on a file stored with the chart
#  foo: {{ .Files.Get "files/etc/foo.xml" | b64enc | quote}}
#  An example of creating a secret based on a value in values.yaml
  bar: {{ .Values.secret.bar | b64enc | quote }}
